-- MySQL Script generated by MySQL Workbench
-- Sun Nov 21 20:11:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`cliente` (
  `cod_cli` VARCHAR(6) NOT NULL,
  `nom_cli` VARCHAR(30) NOT NULL,
  `ape_cli` VARCHAR(30) NOT NULL,
  `sexo_cli` VARCHAR(1) NOT NULL,
  `dni_cli` VARCHAR(8) NOT NULL,
  `tel_cli` VARCHAR(9) NOT NULL,
  `email_cli` VARCHAR(30) NOT NULL,
  `dir_cli` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cod_cli`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurante`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`factura` (
  `num_fac` VARCHAR(8) NOT NULL,
  `cod_cli` VARCHAR(6) NOT NULL,
  `subtotal` VARCHAR(10) NOT NULL,
  `Impuesto` VARCHAR(40) NOT NULL,
  `total` VARCHAR(20) NOT NULL,
  `fec_fac` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`num_fac`),
  INDEX `cod_cli` (`cod_cli` ASC) VISIBLE,
  CONSTRAINT `factura_ibfk_1`
    FOREIGN KEY (`cod_cli`)
    REFERENCES `restaurante`.`cliente` (`cod_cli`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurante`.`platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`platillo` (
  `cod_pla` VARCHAR(6) NOT NULL,
  `descripcion` VARCHAR(30) NOT NULL,
  `precio` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_pla`, `descripcion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurante`.`detallefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`detallefactura` (
  `num_fac` VARCHAR(10) NOT NULL,
  `cod_pla` VARCHAR(6) NOT NULL,
  `des_pla` VARCHAR(30) NOT NULL,
  `cant_pla` VARCHAR(3) NOT NULL,
  `precio` VARCHAR(10) NOT NULL,
  `pre_tot` VARCHAR(10) NOT NULL,
  INDEX `num_fac` (`num_fac` ASC) VISIBLE,
  INDEX `cod_pla` (`cod_pla` ASC) VISIBLE,
  CONSTRAINT `detallefactura_ibfk_1`
    FOREIGN KEY (`num_fac`)
    REFERENCES `restaurante`.`factura` (`num_fac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detallefactura_ibfk_2`
    FOREIGN KEY (`cod_pla`)
    REFERENCES `restaurante`.`platillo` (`cod_pla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurante`.`tiket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`tiket` (
  `num_tik` VARCHAR(8) NOT NULL,
  `cod_cli` VARCHAR(6) NOT NULL,
  `pre_tot` VARCHAR(10) NOT NULL,
  `fecha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`num_tik`),
  INDEX `cod_cli` (`cod_cli` ASC) VISIBLE,
  CONSTRAINT `Tiket_ibfk_1`
    FOREIGN KEY (`cod_cli`)
    REFERENCES `restaurante`.`cliente` (`cod_cli`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurante`.`detalletiket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`detalletiket` (
  `num_tik` VARCHAR(10) NOT NULL,
  `cod_pla` VARCHAR(6) NOT NULL,
  `des_pla` VARCHAR(30) NOT NULL,
  `cant_pla` VARCHAR(3) NOT NULL,
  `precio` VARCHAR(10) NOT NULL,
  `pre_venta` VARCHAR(10) NOT NULL,
  INDEX `num_Tik` (`num_tik` ASC) VISIBLE,
  INDEX `cod_pla` (`cod_pla` ASC) VISIBLE,
  CONSTRAINT `detalleTiket_ibfk_1`
    FOREIGN KEY (`num_tik`)
    REFERENCES `restaurante`.`tiket` (`num_tik`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detalleTiket_ibfk_2`
    FOREIGN KEY (`cod_pla`)
    REFERENCES `restaurante`.`platillo` (`cod_pla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurante`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`empleados` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(25) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`sucursales` (
  `Id_Sucural` INT NOT NULL AUTO_INCREMENT,
  `Cod_Sucural` INT NOT NULL,
  `Nombre_Sucursal` VARCHAR(45) NOT NULL,
  `Departamento_Sucursal` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono_Sucursal` VARCHAR(45) NULL DEFAULT NULL,
  `Num_fac` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Sucural`),
  INDEX `num_fac_idx` (`Num_fac` ASC) VISIBLE,
  CONSTRAINT `num_fac`
    FOREIGN KEY (`Num_fac`)
    REFERENCES `restaurante`.`factura` (`num_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`tipo_usuarios` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(25) NULL DEFAULT NULL,
  `apellidos` VARCHAR(25) NULL DEFAULT NULL,
  `edad` INT NULL DEFAULT NULL,
  `id_tipo_usuario` INT NULL DEFAULT NULL,
  `usuario` VARCHAR(20) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `id_tipo_usuario` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `restaurante`.`tipo_usuarios` (`id_tipo_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
